// Tasks API bodies (API_CONTRACTS §3.9, §3.10; ADR-024).
import { z } from 'zod';
import { LIMITS } from '../constants/limits';
import type { TaskPriority, TaskStatus } from '../constants/statuses';
import type { JsonObject } from '../types/json';
import {
  agentIdSchema,
  metadataSchema,
  progressSchema,
  projectRefSchema,
  taskIdSchema,
  taskPrioritySchema,
  taskStatusSchema,
} from './common';
import {
  booleanDefaultFalse,
  dedupe,
  optionalString,
  optionalValue,
  stripUndefined,
} from './fields';

const titleSchema = z.string().trim().min(1).max(LIMITS.TITLE_MAX);
const descriptionSchema = z.string().trim().max(LIMITS.DESCRIPTION_MAX);
const blockedBySchema = z.array(taskIdSchema).max(LIMITS.BLOCKED_BY_MAX);
const createStatusSchema = z.enum(['todo', 'assigned']);

/** `POST /api/tasks` body after parsing: defaults applied, `blockedBy` deduplicated. */
interface TaskCreateParsed {
  id?: string; // absent → generated by the server (`<taskPrefix>-<n>`)
  title: string;
  description: string | null;
  project: string; // id or name, unresolved
  assignedAgentId: string | null;
  priority: TaskPriority;
  status: 'todo' | 'assigned';
  blockedBy: string[];
  metadata: JsonObject;
}

export const taskCreateSchema = z
  .strictObject({
    id: optionalString(taskIdSchema),
    title: titleSchema,
    description: optionalString(descriptionSchema),
    project: projectRefSchema,
    assignedAgentId: optionalString(agentIdSchema),
    priority: optionalValue(taskPrioritySchema),
    status: optionalValue(createStatusSchema),
    blockedBy: optionalValue(blockedBySchema),
    metadata: optionalValue(metadataSchema),
  })
  .superRefine((body, ctx) => {
    // Cross-field rules (ADR-024).
    if (body.status === 'assigned' && body.assignedAgentId === undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['status'],
        message: 'Status "assigned" requires assignedAgentId',
      });
    }
    if (body.status === 'todo' && body.assignedAgentId !== undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['status'],
        message: 'A task with an assignee must start as "assigned"',
      });
    }
    if (body.id !== undefined && body.blockedBy?.includes(body.id) === true) {
      ctx.addIssue({ code: 'custom', path: ['blockedBy'], message: 'A task cannot block itself' });
    }
  })
  .transform((body): TaskCreateParsed => ({
    ...(body.id === undefined ? {} : { id: body.id }),
    title: body.title,
    description: body.description ?? null,
    project: body.project,
    assignedAgentId: body.assignedAgentId ?? null,
    priority: body.priority ?? 'normal',
    status: body.status ?? (body.assignedAgentId === undefined ? 'todo' : 'assigned'),
    blockedBy: dedupe(body.blockedBy ?? []),
    metadata: body.metadata ?? {},
  }));

/** `PATCH /api/tasks/:id` body after parsing: only provided fields are present (plus `force`). */
interface TaskPatchParsed {
  title?: string;
  description?: string | null; // null (or "" in the body) clears
  status?: TaskStatus;
  priority?: TaskPriority;
  progress?: number;
  assignedAgentId?: string | null; // null unassigns
  blockedBy?: string[]; // replaces the list; deduplicated
  metadata?: JsonObject; // replaces the object
  force: boolean;
}

export const taskPatchSchema = z
  .strictObject({
    title: optionalString(titleSchema),
    description: z
      .string()
      .trim()
      .nullable()
      .transform((value) => (value === '' ? null : value))
      .pipe(descriptionSchema.nullable())
      .optional(),
    status: optionalValue(taskStatusSchema),
    priority: optionalValue(taskPrioritySchema),
    progress: optionalValue(progressSchema),
    assignedAgentId: z
      .string()
      .trim()
      .nullable()
      .transform((value) => (value === '' ? undefined : value))
      .pipe(agentIdSchema.nullable().optional())
      .optional(),
    blockedBy: optionalValue(blockedBySchema),
    metadata: optionalValue(metadataSchema),
    force: booleanDefaultFalse,
  })
  .superRefine((body, ctx) => {
    const provided = Object.entries(body).filter(
      ([key, value]) => key !== 'force' && value !== undefined,
    );
    if (provided.length === 0) {
      ctx.addIssue({ code: 'custom', path: [], message: 'At least one field is required' });
    }
  })
  .transform((body): TaskPatchParsed => {
    const out = stripUndefined(body);
    return out.blockedBy === undefined ? out : { ...out, blockedBy: dedupe(out.blockedBy) };
  });

export type TaskCreateBody = z.input<typeof taskCreateSchema>;
export type TaskCreateInput = z.output<typeof taskCreateSchema>;
export type TaskPatchBody = z.input<typeof taskPatchSchema>;
export type TaskPatchInput = z.output<typeof taskPatchSchema>;
