// Error codes and their HTTP statuses (API_CONTRACTS §2.1, ADR-020/023/027).

export const ERROR_CODES = {
  INVALID_JSON: 'INVALID_JSON', // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR', // 400
  HOST_NOT_ALLOWED: 'HOST_NOT_ALLOWED', // 403 (ADR-027)
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED', // 403 (ADR-037, SEC-2)
  NOT_FOUND: 'NOT_FOUND', // 404
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND', // 404
  TASK_NOT_FOUND: 'TASK_NOT_FOUND', // 404
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION', // 409
  TASK_EXISTS: 'TASK_EXISTS', // 409
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE', // 413
  UNKNOWN_AGENT: 'UNKNOWN_AGENT', // 422
  UNKNOWN_PROJECT: 'UNKNOWN_PROJECT', // 422
  UNKNOWN_TASK: 'UNKNOWN_TASK', // 422
  PROJECT_MISMATCH: 'PROJECT_MISMATCH', // 422
  INTERNAL_ERROR: 'INTERNAL_ERROR', // 500
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE', // 503
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = Object.freeze({
  INVALID_JSON: 400,
  VALIDATION_ERROR: 400,
  HOST_NOT_ALLOWED: 403,
  ORIGIN_NOT_ALLOWED: 403,
  NOT_FOUND: 404,
  AGENT_NOT_FOUND: 404,
  TASK_NOT_FOUND: 404,
  ILLEGAL_TRANSITION: 409,
  TASK_EXISTS: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNKNOWN_AGENT: 422,
  UNKNOWN_PROJECT: 422,
  UNKNOWN_TASK: 422,
  PROJECT_MISMATCH: 422,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});
